workflow:
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH # Only trigger pipeline on master branch

variables:
  VAULT_ADDRESS: https://vault.tag:8200
  VAULT_SKIP_VERIFY: "true"
  NEXUS_URL: https://nexus.tag
  NEXUS_USERNAME: securite

stages:
  - deploy

deploy-hardening:
  stage: deploy
  image: docker.tag/debian-12-hardened:0.0.0
  id_tokens:
    VAULT_ID_TOKEN:
      aud: https://gitlab.com
  variables:
    ARCHIVE_NAME: hardening.tar.gz
  script:
    - apt-get update -qy
    - apt-get install -y curl jq --no-install-recommends

     # Fetch Vault token using Vault API
    - |
      NEXUS_VAULT_TOKEN=$(curl --request POST --insecure \
        --data '{"jwt": "'"$VAULT_ID_TOKEN"'", "role": "gitlab-ci-nexus"}' \
        ${VAULT_ADDRESS}/v1/auth/jwt/login | jq -r .auth.client_token)

      echo $NEXUS_VAULT_TOKEN | cut -c 1-5

    # Fetch Nexus account password using Vault API
    - |
      NEXUS_PASSWORD=$(curl --header "X-Vault-Token: $NEXUS_VAULT_TOKEN" --insecure \
        ${VAULT_ADDRESS}/v1/secret/infra/services/nexus/instances/nexus.tag/users/securite | jq -r '.data."password"')

      echo $NEXUS_PASSWORD | cut -c 1-5

    # Create .tar.gz archive of the repository content excluding this CI config file
    - tar -czvf $ARCHIVE_NAME defaults facts files filter_plugins handlers meta tasks templates

    - TARGET_URL=$NEXUS_URL/repository/raw-hosted/hardening/$ARCHIVE_NAME

    # Upload the archive to Nexus
    - |
      curl -u "${NEXUS_USERNAME}:${NEXUS_PASSWORD}" --upload-file $ARCHIVE_NAME $TARGET_URL

      echo $NEXUS_PASSWORD | cut -c 1-3

  artifacts:
    paths: 
      - "*.tar.gz"