---
- import_tasks: section_1_Initial_Setup.yaml
  become: true
- import_tasks: section_2_Services.yaml
  become: true
- import_tasks: section_3_Network.yaml
  become: true
- import_tasks: section_4_Host_Based_Firewall.yaml
  become: true
- import_tasks: section_5_Access_Control.yaml
  become: true
- import_tasks: section_6_Logging_And_Auditing.yaml
  become: true
- import_tasks: section_7_System_Maintenance.yaml
  become: true
